### ISSUE TITLE
Error 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by nopoz** [prete/OpenFlights-data-converter#1]
I get an error when trying to write the airports-extended.json file. Presumably this is because there is unicode text in the source file? I've commented out the other files in the script as I just need the airports one. 

```
$ ./openflights_to_json.py
Processing airports-extended.dat:
[+] Fetching airports-extended.dat...
[+] Reading airports-extended.dat...
[+] Parsing airports-extended.dat...
[x] Error 'ascii' codec can't encode character u'\xf0' in position 12: ordinal not in range(128)
```

**Comment by prete** [comment]
Hi! I can't seem to reproduce the error. Please check that:
+ you are running this using python 3+
+ that python's default encoding is 'utf-8'

Also, you can comment out the following block inside **parse_and_save** function to check if that is messing up something for you.
```python
for r in data:
  for f in r:
    if r[f] == "\\\\N":
      print(f, r[f])
      r[f] == ""
```

Nevertheless, I've put out a [new release](https://github.com/prete/OpenFlights-data-converter/releases/tag/v0.2-alpha) with the updated json files, in case you can't run the script. 

Hope that helps you.

**Comment by nopoz** [comment]
I was using python2 - using python3 works - thanks for the help!
